# Generated by Django 5.1.7 on 2025-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_veiculo_acessorios_veiculo_acessorios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(related_name='veiculo', to='core.acessorio'),
        ),
    ]
